### ISSUE TITLE
Invalid INTEGER variable type

### ISSUE THREAD

**Issue by XanderPENG** [SalvatoreBarone/pyAMOSA#1]
Hi, dear developers, thx for your project that helped me a lot. However, I have encountered a problem while using it.

Although I have set the types of variables as INTEGER like `types=[AMOSA.Type.INTEGER] * 2`, the `pareto_set` are still continuous REAL numbers like  `[[0.95563459 1.04706615]
 [0.83741398 1.18952123]
 [0.82130937 1.18427941]
 [0.96923262 1.04129043]
 [1.00433428 0.99798579]
 [0.99981262 1.00653311]
 [0.91200459 1.08890229]
 [0.98331718 1.02753961]
 [1.44278925 1.44282007]
 [0.9607519  1.04427449]
 [0.71328101 1.28788821]
 [1.01334248 1.01385571]
 [0.77528897 1.2331641 ]]`

May I enquire if there is any possibility to fix this bug?

**Comment by SalvatoreBarone** [comment]
Hi! Thank you very much for your feedback! I really appreciate that you're using my software! I'll investigate the bug further, and, as soon as I solve the issue you're facing, I'll let you know. I think I can manage it in a couple of days (sorry, I'm really busy!)
In the meanwhile, do you mind posting your code!?

**Comment by SalvatoreBarone** [comment]
I'm unable to reproduce your issue. Please, post your code. Otherwise I'll consider the issue as solved.

**Comment by XanderPENG** [comment]
I am sorry to bother you, it seems that I have made a stupid mistake on setting the variables' types where I set as `types = [0]` instead of `types = [AMOSA.Type.INTEGER]`.

Now I have figured it out and let me say thanks to you and your marvellous project!

**Comment by SalvatoreBarone** [comment]
You're welcome! Again, thank you! I really appreciate that you're using my software!
